nav:
  Home: /
  About: /about/
  Blog: /archives/
  Articles: /articles/
  Imprint: /imprint/

customize:
    gravatar:
        email: ferdinand@muetsch.io
    logo:
        enabled: true
        width: 50
        height: 50
        gravatar: true
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.png
        gravatar: false
      android:
        url: /images/favicon.png
        gravator: false
    social_links:
        github: http://github.com/muety
        twitter: https://twitter.com/n2try
        linkedin: https://www.linkedin.com/in/ferdinand-m%C3%BCtsch-246734139/
        xing: https://www.xing.com/profile/Ferdinand_Muetsch
        telegram: https://telegram.me/n1try
        envelope-o: mailto:ferdinand@muetsch.io
    me_links:
        github: http://github.com/muety
        twitter: https://twitter.com/n2try
        mail: mailto:ferdinand@muetsch.io
    show_all_posts: false
    post_count: 6
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-3922933-8 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus: